### ISSUE TITLE
Decide how to design things that are bound within locations

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#108]
The wilderness is one of these, the only difference is that players are able to attack each other.
Multi areas are one of these as well

**Comment by GregHib** [comment]
We should make use of Kotlins `IntRange` interface that way we can have nice syntax like
`if (player.tile in WILDERNESS) {`

**Comment by kiairatech** [comment]
Locations like the wilderness, pvp zones, multi, and more, are all areas. Activities are things such as minigames.

**Comment by kiairatech** [comment]
> We should make use of Kotlins `IntRange` interface that way we can have nice syntax like
> `if (player.tile in WILDERNESS) {`

Good idea.

**Comment by GregHib** [comment]
Config `areas.yml`

```yaml
surface:
  - range
    x: 2500
    y: 2000
    width: 800
    height: 1000
    planes: 3

lumbridge:
  parents:
    - surface

lumbridge_cow_field:
  parents:
    - lumbridge
# - range...
  - tile
      x: 3260
      y: 3260
      plane: 0
```
Usage
`tile.within("lumbridge")`
```kotlin
fun Entity.checkLocation(): String {
    /*
        If values contains result and result area contains tile
            return area
        if in root area
            recursive check child areas
        else
            save last area to values
            return last area
            
    */
} 
```
```kotlin
data class Area(private val tiles: Set<Int>) {// `in` stuff

fun random() = tiles.random()

fun random(traversal: Traversal): Tile {
    repeat(tile.size) {// a reasonable number but not infinite
        val tile = random() 
        If (!traversal.blocked(tile)) {
            return tile
        } 
    }
    throw exception// what if its a small area? Backup use traversal without entity collision? 
} 
} 
```
